/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import { Hero } from "@/components/Hero";

interface HeroProps {
  breadcrumb: string;
  title: string;
  description: string;
  IndividualsTitle: string;
  ShortDescIndividualsTitle: string;
  BusinessesTitle: string;
  ShortDesBusinessesTitle: string;
  buttonTextIndividuals: string;
  buttonLinkIndividuals: string;
  buttonTextBusinesses: string;
  buttonLinkBusinesses: string;
  className: string;
}

const heroData: HeroProps = {
  breadcrumb: "Breadcrumb Test",
  title: "Vertical Title/Heading",
  description: "Vertical Short Description",
  IndividualsTitle: "Individuals",
  ShortDescIndividualsTitle: "State-Approved Online Training Courses",
  BusinessesTitle: "Businesses",
  ShortDesBusinessesTitle: "Online Training Solutions for Your Teams",
  buttonTextIndividuals: "Browse Courses",
  buttonLinkIndividuals: "http://localhost:3000",
  buttonTextBusinesses: "Contact Us",
  buttonLinkBusinesses: "http://localhost:3000",
  className: "box-border flex relative flex-col shrink-0 mt-5",
};

const MyComponent: React.FC = () => {
  return (
    <main>
      <Hero {...heroData} />
    </main>
  );
};

export default MyComponent;