/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { HeroProduct } from "@/components/HeroProduct";

interface MyComponentProps {}

const MyComponent: React.FC<MyComponentProps> = () => {
  return (
    <main className="box-border flex relative flex-col shrink-0 mt-5">
      <HeroProduct
        shortDescription="Learn everything you need to know about OSHA 29 CFR 1910 standards with the most trusted, OSHA-authorized course for General Industry. Prevent workplace-related injuries and accidents by enrolling today!"
        language="Language Here"
        buttonBuyNowText="Buy Now"
        buttonLinkBuyNow="http://localhost:3000"
        className="box-border flex relative flex-col shrink-0 mt-5"
        duration={null}
      />
    </main>
  );
}

export default MyComponent;